joint1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint1
    joint_speed: 0.5
    motor:
        id: 8
        init: 2047
        min: 0
        max: 4095

